### ISSUE TITLE
My credentials for Facebook & Instagram are bugging. Can I delete and start again?

### ISSUE THREAD

**Issue by johnboymktg** [Gladior-B-V/data-hub-app#46] opened 2024-08-18 08:36 UTC
I originally accessed Datahub via Looker Studio. And granted permissions there. However, Looker Studio didn't register my credentials for FB / IG as authorised.
I went to Data Hub website and decided to add the credentials again or 'Reconnect' them. 
However, it's showing this error and whenever I reconnect the error isn't fixed.
Is there a way for me to delete these credentials and start again? I'm assuming starting from Datahub rather than Looker Studio is advised.

**Comment by rkooiker** [comment] 2024-08-28 12:19
Hi @johnboymktg,

Usually adding the credentials again fixes the issue. Could you share your Data Hub user ID so we can look further into the issue? (found under your profile > edit profile > the greyed out number at the bottom). You can delete the credential by clicking on your workspace at the top of the screen, clicking the three dots on the right > manage credentials > three dots on the right of the credential you want to delete > revoke access, but if the issue is not fixed by reconnecting i'm afraid that this will not solve it either.

**Closed as completed** 2024-09-11 08:56 UTC
